package com.vts.pfms.cars.service;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.multipart.MultipartFile;

import com.vts.pfms.cars.dto.CARSRSQRDetailsDTO;
import com.vts.pfms.cars.dto.CARSApprovalForwardDTO;
import com.vts.pfms.cars.dto.CARSContractDetailsDTO;
import com.vts.pfms.cars.model.CARSContract;
import com.vts.pfms.cars.model.CARSContractConsultants;
import com.vts.pfms.cars.model.CARSContractEquipment;
import com.vts.pfms.cars.model.CARSInitiation;
import com.vts.pfms.cars.model.CARSInitiationTrans;
import com.vts.pfms.cars.model.CARSOtherDocDetails;
import com.vts.pfms.cars.model.CARSRSQRDeliverables;
import com.vts.pfms.cars.model.CARSRSQRMajorRequirements;
import com.vts.pfms.cars.model.CARSSoC;
import com.vts.pfms.cars.model.CARSSoCMilestones;
import com.vts.pfms.cars.model.CARSSoCMilestonesProgress;
import com.vts.pfms.committee.dto.ActionAssignDto;
import com.vts.pfms.committee.dto.ActionMainDto;
import com.vts.pfms.model.LabMaster;

public interface CARSService {

	public List<Object[]> carsInitiationList(String LoginType, String EmpId) throws Exception;
	public CARSInitiation getCARSInitiationById(long carsIntiationId) throws Exception;
	public long addCARSInitiation(CARSInitiation initiation,String labcode) throws Exception;
	public long editCARSInitiation(CARSInitiation initiation) throws Exception;
	public Object[] carsRSQRDetails(String carsinitiationid) throws Exception;
	public long carsRSQRDetailsSubmit(String carsInitiationId, String attributes, String details, String userId) throws Exception;
	public long carsRSQRDetailsUpdate(String carsInitiationId, String attributes, String details, String userId) throws Exception;
	public List<CARSRSQRMajorRequirements> getCARSRSQRMajorReqrByCARSInitiationId(long carsInitiationId) throws Exception;
	public List<CARSRSQRDeliverables> getCARSRSQRDeliverablesByCARSInitiationId(long carsInitiationId) throws Exception;
	public long carsRSQRMajorReqrDetailsSubmit(CARSRSQRDetailsDTO dto) throws Exception;
	public int removeCARSRSQRMajorReqrDetails(long carsInitiationId) throws Exception;
	public long carsRSQRDeliverableDetailsSubmit(CARSRSQRDetailsDTO dto) throws Exception;
	public int removeCARSRSQRDeliverableDetails(long carsInitiationId) throws Exception;
	public long rsqrApprovalForward(CARSApprovalForwardDTO dto,HttpServletRequest req, HttpServletResponse res, String labcode) throws Exception;
	public Object[] getEmpGDEmpId(String empId) throws Exception;
	public Object[] getEmpPDEmpId(String projectId) throws Exception;
	public Object[] getEmpDetailsByEmpId(String empId) throws Exception;
	public List<Object[]> carsTransApprovalData(String carsInitiationId, String apprFor) throws Exception;
	public List<Object[]> carsRSQRPendingList(String empId) throws Exception;
	public List<Object[]> carsRSQRApprovedList(String empId, String FromDate, String ToDate, String type) throws Exception;
	public Object[] getEmpDataByLoginType(String loginType) throws Exception;
	public CARSSoC getCARSSoCById(long carsSoCId) throws Exception;
	public long addCARSSoC(CARSSoC soc, MultipartFile sooFile, MultipartFile frFile, MultipartFile executionPlan) throws Exception;
	public long editCARSSoC(CARSSoC soc, MultipartFile sooFile, MultipartFile frFile, MultipartFile executionPlan) throws Exception;
	public int invForSoODateSubmit(String carsInitiationId, String sooDate) throws Exception;
	public CARSSoC getCARSSoCByCARSInitiationId(long carsInitiationId) throws Exception;
	public void carsRSQRFormFreeze(HttpServletRequest req, HttpServletResponse res, long carsInitiationId) throws Exception;
	public long socApprovalForward(CARSApprovalForwardDTO dto) throws Exception;
	public long addCARSInitiationTransaction(CARSInitiationTrans transaction) throws Exception;
	public long carsUserRevoke(String carsInitiationId, String username, String empId, String carsStatusCode, String labcode) throws Exception;
	public List<CARSSoCMilestones> getCARSSoCMilestonesByCARSInitiationId(long carsInitiationId) throws Exception;
	public long carsSoCMilestonesDetailsSubmit(CARSRSQRDetailsDTO dto) throws Exception;
	public int removeCARSSoCMilestonesDetails(long carsInitiationId) throws Exception;
	public List<Object[]> carsSoCMoMUploadedList(String fromdate, String todate) throws Exception;
	public long editCARSSoC(CARSSoC soc) throws Exception;
	public long dpcSoCApprovalForward(CARSApprovalForwardDTO dto) throws Exception;
	public Object[] getApprAuthorityDataByType(String labcode, String type) throws Exception;
	public Object[] getLabDirectorData(String labcode) throws Exception;
	public List<Object[]> carsDPandCSoCPendingList(String empId, String labcode) throws Exception;
	public long carsSoCDPCRevoke(String carsInitiationId, String userId, String empId, String labcode) throws Exception;
	public List<Object[]> carsDPCSoCApprovedList(String empId, String FromDate, String ToDate) throws Exception;
	public List<Object[]> carsTransListByType(String carsInitiationId, String statusFor) throws Exception;
	public List<Object[]> carsRemarksHistoryByType(String carsInitiationId, String remarksFor) throws Exception;
	public long carsSoCUploadMoM(MultipartFile momFile, String labcode, String carsInitiationId, String EmpId, String UserId, String MoMFlag) throws Exception;
	public List<Object[]> getLabList(String lab) throws Exception;
	public List<Object[]> getEmployeeListByLabCode(String labCode) throws Exception;
	public LabMaster getLabDetailsByLabCode(String labcode) throws Exception;
	public List<Object[]> carsDPCSoCFinalApprovedList(String fromdate, String todate) throws Exception;
	public CARSContract getCARSContractByCARSInitiationId(long carsInitiationId) throws Exception;
	public List<CARSContractConsultants> getCARSContractConsultantsByCARSInitiationId(long carsInitiationId) throws Exception;
	public List<CARSContractEquipment> getCARSContractEquipmentByCARSInitiationId(long carsInitiationId) throws Exception;
	public long addCARSContractDetails(CARSContract contract) throws Exception;
	public long editCARSContractDetails(CARSContract contract) throws Exception;
	public long addCARSContractConsultantsDetails(CARSContractDetailsDTO dto) throws Exception;
	public long addCARSContractEquipmentDetails(CARSContractDetailsDTO dto) throws Exception;
	public long carsFinalReportEditSubmit(CARSContract contract, String firstTime,String labcode) throws Exception;
	public List<CARSOtherDocDetails> getCARSOtherDocDetailsByCARSInitiationId(long carsInitiationId) throws Exception;
	public long CARSCSDocDetailsSubmit(CARSOtherDocDetails doc, MultipartFile attatchFlagA, MultipartFile attatchFlagB, MultipartFile attatchFlagC, String EmpId, String labcode) throws Exception;
	public long CARSCSDocDetailsUpdate(CARSOtherDocDetails doc, MultipartFile attatchFlagA, MultipartFile attatchFlagB, MultipartFile attatchFlagC) throws Exception;
	public Object[] carsStatusDetailsByCARSInitiationId(long carsInitiationId) throws Exception;
	public CARSOtherDocDetails getCARSOtherDocDetailsById(long otherDocDetailsId) throws Exception;
	public long othersCSApprovalForward(CARSApprovalForwardDTO dto,String labcode) throws Exception;
	public List<Object[]> carsCSPendingList(String empId, String labcode) throws Exception;
	public List<Object[]> carsCSApprovedList(String empId, String FromDate, String ToDate) throws Exception;
	public long carsCSDoCRevoke(String carsInitiationId, String userId, String empId, String labcode) throws Exception;
	public long carsCSDocUpload(MultipartFile otherdocfile, String otherDocDetailsId) throws Exception;
	public List<Object[]> carsRemarksHistoryByMilestoneNo(String carsInitiationId, String milestoneNo) throws Exception;
	public List<Object[]> carsTransApprovalDataByMilestoneNo(String carsInitiationId, String milestoneNo);
	public long CARSMPDocDetailsSubmit(CARSOtherDocDetails doc, MultipartFile attatchFlagA, MultipartFile attatchFlagB, MultipartFile attatchFlagC, String EmpId, String labcode) throws Exception;
	public long CARSMPDocDetailsUpdate(CARSOtherDocDetails doc, MultipartFile attatchFlagA, MultipartFile attatchFlagB, MultipartFile attatchFlagC) throws Exception;
	public long othersMPApprovalForward(CARSApprovalForwardDTO dto, String labcode) throws Exception;
	public List<Object[]> carsMPPendingList(String empId, String labcode) throws Exception;
	public List<Object[]> carsMPApprovedList(String empId, String FromDate, String ToDate) throws Exception;
	public List<Object[]> carsMPStatusDetailsByCARSInitiationId(long carsInitiationId) throws Exception;
	public long carsMPDoCRevoke(String carsInitiationId, String userId, String empId, String milestoneNo, String labcode) throws Exception;
	public long carsMPDocUpload(MultipartFile otherdocfile, String otherDocDetailsId) throws Exception;
	public long CARSPTCDocDetailsSubmit(CARSOtherDocDetails doc) throws Exception;
	public long CARSPTCDocDetailsUpdate(CARSOtherDocDetails doc) throws Exception;
	public List<Object[]> ExpertEmployeeList() throws Exception;
	public int finalSoODateSubmit(String carsInitiationId, String date) throws Exception;
	public Long carsMilestoneActionMainInsert(ActionMainDto mainDto, ActionAssignDto assign) throws Exception;
	public List<Object[]> assignedListByCARSSoCMilestoneId(String carsSoCMilestoneId) throws Exception;
	public CARSSoCMilestones getCARSSoCMilestonesById(String carsSoCMilestoneId) throws Exception;
	public long addCARSSoCMilestonesProgress(CARSSoCMilestonesProgress milestoneProgress) throws Exception;
	public List<CARSSoCMilestonesProgress> getCARSSoCMilestonesProgressListByCARSSoCMilestoneId(String carsSoCMilestoneId) throws Exception;
	public List<Object[]> getAllCARSSoCMilestonesProgressList() throws Exception;
	public List<CARSSoCMilestones> getAllCARSSoCMilestonesList() throws Exception;
	public List<CARSContract> getAllCARSContractList() throws Exception;
	public List<CARSOtherDocDetails> getCARSOtherDocDetailsList() throws Exception;
	public int carsCurrentStatusUpdate(String currentStatus, String carsInitiationId) throws Exception;
	
}
