package com.vts.pfms.project.service;

import java.util.List;

import com.vts.pfms.print.model.ProjectTechnicalWorkData;
import com.vts.pfms.project.dto.PfmsInitiationAttachmentDto;
import com.vts.pfms.project.dto.PfmsInitiationAttachmentFileDto;
import com.vts.pfms.project.dto.PfmsInitiationAuthorityDto;
import com.vts.pfms.project.dto.PfmsInitiationAuthorityFileDto;
import com.vts.pfms.project.dto.PfmsInitiationCostDto;
import com.vts.pfms.project.dto.PfmsInitiationDetailDto;
import com.vts.pfms.project.dto.PfmsInitiationDto;
import com.vts.pfms.project.dto.PfmsProjectDataDto;
import com.vts.pfms.project.dto.PfmsProjectTccDto;
import com.vts.pfms.project.dto.PfmsRiskDto;
import com.vts.pfms.project.dto.ProjectAssignDto;
import com.vts.pfms.project.dto.ProjectMasterAttachDto;
import com.vts.pfms.project.dto.ProjectScheduleDto;
import com.vts.pfms.project.model.PfmsInitiationAttachmentFile;
import com.vts.pfms.project.model.PfmsInitiationAuthorityFile;
import com.vts.pfms.project.model.PfmsInitiationChecklistData;
import com.vts.pfms.project.model.ProjectAssign;
import com.vts.pfms.project.model.ProjectMain;
import com.vts.pfms.project.model.ProjectMaster;
import com.vts.pfms.project.model.ProjectMasterRev;

public interface ProjectService {

	public List<Object[]> ProjectIntiationList(String Empid,String LoginType,String LabCode) throws Exception ;
	public List<Object[]> ProjectTypeList() throws Exception;
	public List<Object[]> OfficerList() throws Exception;
	public Long ProjectMainAdd(ProjectMain proType ) throws Exception;
	public Long ProjectMainEdit(ProjectMain proType ) throws Exception;
	public Object[] ProjectMainEditData(String ProjectMainId) throws Exception ;
	public Long ProjectMainClose(ProjectMain proType) throws Exception;
	public List<Object[]> PfmsCategoryList() throws Exception;
	public List<Object[]> PfmsDeliverableList() throws Exception;
	public List<Object[]> InitiatedProjectList() throws Exception;
	public List<Object[]> LabList(String IntiationId) throws Exception;
	public Long ProjectIntiationAdd(PfmsInitiationDto pfmsinitiationdto,String UserId,String EmpId,String EmpName ) throws Exception;
	public Long ProjectShortNameCount(String ProjectShortName) throws Exception;
	public List<Object[]> ProjectDetailes(Long IntiationId) throws Exception;
	//public Object[] ProjectDetailes(Long IntiationId) throws Exception;
	public List<Object[]> ProjectDetailsPreview(Long IntiationId) throws Exception;
	public Long ProjectIntiationAdd(PfmsInitiationDetailDto pfmsinitiationdetaildto,String UserId ) throws Exception;
	public List<Object[]> BudgetItem(String BudegtId) throws Exception;
	public List<Object[]> ProjectIntiationItemList(String InitiationId) throws Exception;
	public Long ProjectIntiationCostAdd(PfmsInitiationCostDto pfmsinitiationcostdto,String UserId,Object[] ProjectCost ) throws Exception;
	public int ProjectLabAdd(String [] LabId,String InitiationId,String UserId) throws Exception;
	public List<Object[]> ProjectIntiationLabList(String InitiationId) throws Exception;
	public List<Object[]> BudgetHead() throws Exception;
	public Long ProjectScheduleAdd(String[] MilestoneActivity,String[] MilestoneMonth,String[] MilestoneRemark,String InitiationId,String UserId,Object[] ProjectDetailes,Integer TotalMonth) throws Exception;
	//Line Added
	public Long ProjectScheduleAdd(String[] MilestoneActivity,String[] MilestoneMonth,int MilestoneTotalMonth, int Milestonestartedfrom,String[] MilestoneRemark,String InitiationId,String UserId,Object[] ProjectDetailes,Integer TotalMonth) throws Exception;
	public List<Object[]> ProjectIntiationScheduleList(String InitiationId) throws Exception;
	//Line Added
	public List<Object[]>ProjectScheduleTotalMonthList(String InitiationId)throws Exception;
	/*L.A*/public List<Object[]>MileStonenoTotalMonths(String InitiationId,int msno) throws Exception;
	public Object[] ProjectProgressCount(String InitiationId) throws Exception;
	public List<Object[]> ProjectIntiationDetailsList(String InitiationId) throws Exception;
	public List<Object[]> ProjectIntiationCostList(String InitiationId) throws Exception;
	public List<Object[]> ProjectEditData(String IntiationId) throws Exception;
	public int ProjectIntiationEdit(PfmsInitiationDto pfmsinitiationdto,String UserId ) throws Exception;
	public Double TotalIntiationCost(String IntiationId) throws Exception;
	public List<Object[]> ProjectCostEditData(String InitiationCostId) throws Exception;
	public int ProjectIntiationCostEdit(PfmsInitiationCostDto pfmsinitiationcostdto,String UserId,String InitiationId,String TotalCost ) throws Exception;
	public long ProjectScheduleEdit(ProjectScheduleDto projectschedule) throws Exception;
	/*L.A*/public int MilestoneTotalMonthUpdate( int newMilestoneTotalMonth,String IntiationId, String milestoneno) throws Exception;
	public int ProjectScheduleDelete(String InitiationScheduleId,String UserId,Integer MilestoneScheduleMonth,String InitiationId) throws Exception;
	public Long ProjectInitiationDetailsUpdate(PfmsInitiationDetailDto pfmsinitiationdetaildto,String UserId,String Details) throws Exception;
	public Integer ProjectScheduleMonth(String InitiationId) throws Exception;
	public Integer ProjectDurationMonth(String InitiationId) throws Exception;
	/*L.A*/public Integer MilestoneScheduleMonth(String initiationscheduleid,String IntiationId)throws Exception;
	public int ProjectScheduleEditData(String InitiationScheduleId) throws Exception;
	/*L.A*/ public int mileStonemonthprevious(String IntiationId, String milestoneno) throws Exception;
	/*L.A*/ public int milestonenototalmonth(String IntiationId, String milestoneno) throws Exception;
	public Long ProjectInitiationAttachmentAdd(PfmsInitiationAttachmentDto pfmsinitiationattachmentdto,PfmsInitiationAttachmentFileDto pfmsinitiationattachmentfiledto,String UserId) throws Exception;
	public List<Object[]> ProjectIntiationAttachment(String InitiationId) throws Exception;
	public List<Object[]> AuthorityAttachment(String InitiationId) throws Exception;
	
	public PfmsInitiationAttachmentFile ProjectIntiationAttachmentFile(String InitiationAttachmentId) throws Exception;
	public Object[] ProjectIntiationFileName(long InitiationAttachmentId) throws Exception;
	public int ProjectInitiationAttachmentDelete(String InitiationAttachmentId,String UserId) throws Exception;
	public int ProjectInitiationAttachmentUpdate(String InitiationAttachmentId,String FileName,String UserId) throws Exception;
	public String ProjectIntiationAttachmentFileName(String InitiationAttachmentId) throws Exception;
	public String ProjectIntiationAttachmentFileNamePath(String InitiationAttachmentId) throws Exception;
	public int ProjectLabDelete(String initiationlabid,String InitiationId,String UserId) throws Exception;
	public int ProjectIntiationCostDelete(String initiationcostid, String UserId,String InitiationId) throws Exception ;
	public int ProjectIntiationStatusUpdate(String InitiationId,String UserId,String EmpId,String ProjectCode) throws Exception;
	public Long ProjectForwardStatus(String InitiationId) throws Exception;
	public List<Object[]> ProjectActionList(String ProjectAuthorityId) throws Exception;
	public List<Object[]> ProjectApprovePdList(String EmpId) throws Exception;
	public int ProjectApprovePd(String InitiationId,String Remark,String UserId,String EmpId,String ProjectCode,String Status) throws Exception;
	public List<Object[]> EmployeeList(String LabCode) throws Exception;
	public List<Object[]> ProjectStatusList(String EmpId,String LoginType,String LabCode)throws Exception;
	public List<Object[]> ProjectApprovalTracking(String InitiationId) throws Exception;
	public List<Object[]> ProjectApproveRtmddoList(String EmpId) throws Exception;
	public int ProjectApproveRtmddo(String InitiationId,String Remark,String UserId,String EmpId,String ProjectCode,String Status) throws Exception;
	public List<Object[]> ProjectApproveTccList(String EmpId) throws Exception;
	public int ProjectApproveTcc(String InitiationId,String Remark,String UserId,String EmpId,String ProjectCode,String Status) throws Exception;
	public Double TotalIntiationFeCost(String IntiationId) throws Exception;
	public Double TotalIntiationReCost(String IntiationId) throws Exception;
	public List<Object[]> ProjectCost(Long IntiationId) throws Exception;
	public List<Object[]> TccProjectList() throws Exception;
	public List<Object[]> ExpertList() throws Exception;
	public List<Object[]> ProjectList()throws Exception;
	public List<Object[]> ProjectTypeMainList()throws Exception;
	public List<Object[]> ProjectCategoryList()throws Exception;
	public Long ProjectMasterAdd(ProjectMaster proType) throws Exception;
	public Long ProjectEdit(ProjectMaster proType) throws Exception;
	public Long ProjectClose(ProjectMaster proType) throws Exception ;	
	public Object[] ProjectEditData1(String ProjectId) throws Exception;	
	public List<Object[]> getProjectList() throws Exception;
	public List<Object[]> ProjectAssignList(String EmpId)throws Exception;
	public List<Object[]> UserList(String proId) throws Exception;
	public Object[] ProjectData(String ProId)throws Exception;
	public Long ProjectAssignAdd(ProjectAssignDto proAssigndto ) throws Exception;
	public Long ProjectRevoke(ProjectAssign proAssign ) throws Exception;
	public List<Object[]> ProjectApproveAdList(String EmpId) throws Exception;
	public int ProjectApproveAd(String InitiationId, String Remark, String UserId, String EmpId,String ProjectCode,String Status) throws Exception;
	public List<Object[]> ApprovalStutusList(String InitiationId) throws Exception;
	public long ProjectDataSubmit(PfmsProjectDataDto dto) throws Exception;
	public List<Object[]> ProjectStageDetailsList() throws Exception;
	public Object[] ProjectDataDetails(String projectid) throws Exception;
	public long ProjectDataEditSubmit(PfmsProjectDataDto dto) throws Exception;
	public Object[] ProjectDataSpecsFileData(String projectdataid) throws Exception;
	public long ProjectDataRevSubmit(PfmsProjectDataDto projectdatadto) throws Exception;
	public List<Object[]> ProjectDataRevList(String projectid) throws Exception;
	public Object[] ProjectDataSpecsRevFileData(String projectdatarevid) throws Exception;
	public List<Object[]> InitiatedProjectDetails(String ProjectId) throws Exception;
	public List<Object[]> NodalLabList() throws Exception;
	public Object[] ProjectDataRevData(String projectdatarevid) throws Exception;
	public List<Object[]> ProjectRiskDataList(String projectid,String LabCode) throws Exception;
	public Object[] ProjectRiskData(String actionmainid) throws Exception;
	public long ProjectRiskDataSubmit(PfmsRiskDto dto) throws Exception;
	public Object[] ProjectRiskMatrixData(String actionmainid) throws Exception;
	public long ProjectRiskDataEdit(PfmsRiskDto dto) throws Exception;
	public long ProjectRiskDataRevSubmit(PfmsRiskDto dto) throws Exception;
	public List<Object[]> ProjectRiskMatrixRevList(String actionmainid) throws Exception;
	public List<Object> RiskDataPresentList(String projectid,String LabCode) throws Exception;
	public Long ProjectInitiationAuthorityAdd(PfmsInitiationAuthorityDto pfmsinitiationauthoritydto,String UserId,PfmsInitiationAuthorityFileDto pfmsinitiationauthorityfiledto) throws Exception;
 	public PfmsInitiationAuthorityFile ProjectAuthorityDownload(String AuthorityFileId) throws Exception;
 	public Long ProjectAuthorityUpdate(PfmsInitiationAuthorityDto pfmsinitiationauthoritydto,PfmsInitiationAuthorityFileDto pfmsinitiationauthorityfiledto,String UserId) throws Exception;
	public List<Object[]> getProjectCatSecDetalis(String projectmainId)throws Exception;
	public List<Object[]> LoginProjectDetailsList(String empid,String Logintype,String LabCode) throws Exception;
	public List<Object[]> ProjectApprovalFlowEmpData(String empid,String LabCode) throws Exception;
	public List<Object[]> ProjectMainList() throws Exception;
	public long ProjectMainToMaster(String projectmainid, String user,String LabCode) throws Exception;
	public ProjectMasterRev ProjectMasterREVSubmit(String projectid, String userid, String remarks) throws Exception;
	public List<Object[]> ProjectTypeMainListNotAdded() throws Exception;
	public List<Object[]> ProjectRevList(String projectid) throws Exception;
	public long ProjectMasterAttachAdd(ProjectMasterAttachDto dto) throws Exception;
	public List<Object[]> ProjectMasterAttachList(String projectid) throws Exception;
	public Object[] ProjectMasterAttachData(String projectattachid) throws Exception;
	public int ProjectMasterAttachDelete(String projectattachid) throws Exception;
	public long TechnicalWorkDataAdd(ProjectTechnicalWorkData modal) throws Exception;
	public long TechnicalWorkDataEdit(ProjectTechnicalWorkData modal,String techdataid) throws Exception;
	public List<Object[]> InitiationCheckList(String initiationid) throws Exception;
	public long IntiationChecklistUpdate(PfmsInitiationChecklistData cldata) throws Exception;
	public List<Object[]> RiskTypeList() throws Exception;
}
